### ISSUE TITLE
Advanced Debug Menu Crash: java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by kvverti** [TallWorlds/CubicChunks#9]
This crash is triggered when SHIFT+F3 is pressed as the CPU pie graph is loaded.

---- Minecraft Crash Report ----
// You're mean.

Time: 4/21/15 4:59 PM
Description: Exception in world tick

java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.remove(ArrayList.java:495)
    at net.minecraft.profiler.Profiler.endSection|getProfileData(Profiler.java:70)
    at net.minecraft.profiler.Profiler.startSection|getSectionName(Profiler.java:141)
    at cubicchunks.lighting.DiffuseLightingCalculator.calculate(DiffuseLightingCalculator.java:82)
    at cubicchunks.lighting.LightingManager.computeDiffuseLighting(LightingManager.java:68)
    at cubicchunks.CubicChunkSystem.updateLightingAt(CubicChunkSystem.java:324)
    at cuchaz.m3l.classTransformation.transformers.WorldTransformer.updateLightingAt(WorldTransformer.java:188)
    at net.minecraft.world.World.getMoonPhase|updateLightingAt(World.java:2049)
    at cubicchunks.world.column.Column.m(Column.java:770)
    at net.minecraft.world.World.onEntityAdded|playSoundAtEntity|getPlayerEntityByName|getEntities|getBlockCollisionBoxes|updateSurroundingBlocksExcludingFacing|a|updateEntity|addLevelAccess|findEntityNearest|isBlockProtected|checkBlockIsValidAttachmentSurface|isEntityInsideWorldBorder|isAnyMaterialInRegion|tickPending|checkBlockRangeIsInWorld|getLightFromNeighbors|checkBlockRangeIsInWorld|getPowerTransmittedFromLocationFacing|setWorldInfoInitialized|setGameTime|getScheduledBlockTicks|raytraceBlocks|playSoundAtPlayer|createExplosion|isBlockTickPending|checkBlockRangeIsInWorld|raytraceBlocks|setBlockState|putOutFacingFire|countEntitiesExceptMobsRequiringPersistence|checkBlockRangeIsInWorld|isBlockLoaded|setAllowedSpawnTypes|setBlockEntity|a|checkChunkExists|isBlockInWorld|getRandom|getWatchersInRange|markBlocksDirtyVertical|checkBlockRangeIsInWorld|playWorldEvent|addBlockEntities|getChunk|getEntities|addBlockEntity|checkBlockRangeIsInWorld|getScheduledBlockTicks|canBlockBePlaced|playEffect|tickBlockAtPosImmediately|getFeatureClosestToPosition|hasNoEntitiesInUnrelatedTo|getEntities|scheduleBlockTick|checkEntityIsIn|broadcastSound|updateSoundAndLights|spawnParticle|createExplosion|playRecord|findEntitiesExcept|raytraceBlocks|playSoundAtLocation|a|getWatchersInRange|getEntity|getCalculatedLightAt|addLevelInfoToCrashReport|tryPlaceBlock|getSkylightReduction|setLightAt|getWeatherSomethingVec|spawnParticle|a|playSoundEffect|scheduleBlockTick|a|a(World.java:1978)
    at net.minecraft.world.WorldClient.tickBlocks(WorldClient.java:122)
    at net.minecraft.world.WorldClient.tick(WorldClient.java:87)
    at net.minecraft.main.Minecraft.tick(Minecraft.java:1866)
    at net.minecraft.main.Minecraft.runGameLoop(Minecraft.java:888)
    at net.minecraft.main.Minecraft.setCrashReporter|setViewEntity|displayGuiScreen|runTask|run|loadWorld|addServerStatsToSnooper|setServerData(Minecraft.java:325)
    at null.main(null.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.util.ArrayList.elementData(ArrayList.java:418)
    at java.util.ArrayList.remove(ArrayList.java:495)
    at net.minecraft.profiler.Profiler.endSection|getProfileData(Profiler.java:70)
    at net.minecraft.profiler.Profiler.startSection|getSectionName(Profiler.java:141)
    at cubicchunks.lighting.DiffuseLightingCalculator.calculate(DiffuseLightingCalculator.java:82)
    at cubicchunks.lighting.LightingManager.computeDiffuseLighting(LightingManager.java:68)
    at cubicchunks.CubicChunkSystem.updateLightingAt(CubicChunkSystem.java:324)
    at cuchaz.m3l.classTransformation.transformers.WorldTransformer.updateLightingAt(WorldTransformer.java:188)
    at net.minecraft.world.World.getMoonPhase|updateLightingAt(World.java:2049)
    at cubicchunks.world.column.Column.m(Column.java:770)
    at net.minecraft.world.World.onEntityAdded|playSoundAtEntity|getPlayerEntityByName|getEntities|getBlockCollisionBoxes|updateSurroundingBlocksExcludingFacing|a|updateEntity|addLevelAccess|findEntityNearest|isBlockProtected|checkBlockIsValidAttachmentSurface|isEntityInsideWorldBorder|isAnyMaterialInRegion|tickPending|checkBlockRangeIsInWorld|getLightFromNeighbors|checkBlockRangeIsInWorld|getPowerTransmittedFromLocationFacing|setWorldInfoInitialized|setGameTime|getScheduledBlockTicks|raytraceBlocks|playSoundAtPlayer|createExplosion|isBlockTickPending|checkBlockRangeIsInWorld|raytraceBlocks|setBlockState|putOutFacingFire|countEntitiesExceptMobsRequiringPersistence|checkBlockRangeIsInWorld|isBlockLoaded|setAllowedSpawnTypes|setBlockEntity|a|checkChunkExists|isBlockInWorld|getRandom|getWatchersInRange|markBlocksDirtyVertical|checkBlockRangeIsInWorld|playWorldEvent|addBlockEntities|getChunk|getEntities|addBlockEntity|checkBlockRangeIsInWorld|getScheduledBlockTicks|canBlockBePlaced|playEffect|tickBlockAtPosImmediately|getFeatureClosestToPosition|hasNoEntitiesInUnrelatedTo|getEntities|scheduleBlockTick|checkEntityIsIn|broadcastSound|updateSoundAndLights|spawnParticle|createExplosion|playRecord|findEntitiesExcept|raytraceBlocks|playSoundAtLocation|a|getWatchersInRange|getEntity|getCalculatedLightAt|addLevelInfoToCrashReport|tryPlaceBlock|getSkylightReduction|setLightAt|getWeatherSomethingVec|spawnParticle|a|playSoundEffect|scheduleBlockTick|a|a(World.java:1978)
    at net.minecraft.world.WorldClient.tickBlocks(WorldClient.java:122)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [bex['kwerti'/0, l='MpServer', x=-871.30, y=152.67, z=107.61]]
    Chunk stats: MultiplayerChunkCache: 1042, 1042
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -261.00,1.00,171.00 - World: (-261,1,171), Chunk: (at 11,0,11 in -17,10; contains blocks -272,0,160 to -257,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 9282 game time, 1467 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [bex['kwerti'/0, l='MpServer', x=-871.30, y=152.67, z=107.61]]
    Retry entities: 0 total; []
    Server brand: vanilla
    Server type: Integrated singleplayer server
Stacktrace:
    at bdc.a(bdc.java:309)
    at avf.s(avf.java:1873)
    at avf.av(avf.java:888)
    at avf.a(avf.java:325)
    at net.minecraft.client.main.Main.main(Main.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [bex['kwerti'/0, l='MpServer', x=-871.30, y=152.67, z=107.61]]
    Chunk stats: MultiplayerChunkCache: 1042, 1042
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: -261.00,1.00,171.00 - World: (-261,1,171), Chunk: (at 11,0,11 in -17,10; contains blocks -272,0,160 to -257,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 9282 game time, 1467 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 1 total; [bex['kwerti'/0, l='MpServer', x=-871.30, y=152.67, z=107.61]]
    Retry entities: 0 total; []
    Server brand: vanilla
    Server type: Integrated singleplayer server

-- System Details --
Details:
    Minecraft Version: 1.8.3
    Operating System: Windows 7 (amd64) version 6.1
    CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Java Version: 1.8.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 837888720 bytes (799 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 24, tallocated: 82
    Launched Version: M3L
    LWJGL: 2.9.4
    OpenGL: AMD Radeon HD 6700 Series GL version 4.2.11931 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: [Argon-32x_Vanilla_v1.10.0.zip]
Current Language: ~~ERROR~~ NullPointerException: null
Profiler Position: [UNKNOWN]
```

**Comment by kvverti** [comment]
Perhaps a way to attach files?

**Comment by Razaekel** [comment]
Can't attach files to github issues, put it on something like pastebin and add a link.
